import "./globals.css";
import { Inter } from "next/font/google";
import "focus-visible";
// eslint-disable-next-line @next/next/no-document-import-in-page
import HeaderComponent from "@/components/header";
import Footer from "@/components/footer";
import { Metadata } from "next/types";
import headerLogo from "@/Images/Logo.jpeg";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Coding Brothers",
  description: "Generated by Coding Brothers AI",
};

// const RootLayout = ({ children }: { children: React.ReactNode }) => {
//   return (
//     <html lang="en" className="h-full">
//       <body className={`${inter.className} h-full`}>{children}</body>
//     </html>
//   );
// };

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html className="h-full antialiased" lang="en">
      <body className="flex h-full flex-col bg-zinc-50 dark:bg-black">
        <div>
          <div className="fixed inset-0 flex justify-center sm:px-8">
            <div className="flex w-full max-w-7xl lg:px-8">
              <div className="w-full bg-white ring-1 ring-zinc-100 dark:bg-zinc-900 dark:ring-zinc-300/20"></div>
            </div>
          </div>
          <div className="relative">
            <HeaderComponent />
            <div></div>
            <main>{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className="h-full">
//       <body className={`${inter.className} h-full`}>{children}</body>
//     </html>
//   );
// }
